Feat: ilk for Acceptance Test
clio-finance/socgen-ofh-onboarding pull request #27
Opened 2022-02-24 23:25 UTC by hbarcelos

2022-03-01 12:50 UTC, lollike commented on src/RwaLiquidationOracle2.sol
> -// Copyright (C) 2020, 2021 Lev Livnev <lev@liv.nev.org.uk>
Maybe we should save this contract somewhere else, in case we need it in the future?

2022-03-01 13:09 UTC, lollike requested changes

2022-03-01 13:09 UTC, nikozalo commented on src/RwaUrnUtils.sol
> +// Copyright (C) 2020, 2021 Lev Livnev <lev@liv.nev.org.uk>
Why credit Lev here? This is a brand new contract no?

2022-03-01 13:09 UTC, nikozalo commented on src/RwaUrnUtils.t.sol
> +// Copyright (C) 2020, 2021 Lev Livnev <lev@liv.nev.org.uk>
Same question as previous contract

2022-03-01 13:09 UTC, lollike commented on src/RwaUrnUtils.t.sol
> +        vat.suck(VOW, who, rad(wad));
Suck mints Dai as well, you are minting 2x wad Dai here. What's the reasoning for this? Why even have the suck step, if you can just mint Dai directly?

2022-03-01 13:15 UTC, hbarcelos commented on src/RwaUrnUtils.sol
> +// Copyright (C) 2020, 2021 Lev Livnev <lev@liv.nev.org.uk>
This was just copied over I guess.

2022-03-07 14:40 UTC, nduchak approved these changes

2022-03-08 01:42 UTC, canokaue approved these changes

2022-03-08 15:31 UTC, merged